🐋👌Add VC Redistributable to base images for python package compatibility
s-weigand/uv-windows-docker pull request #3
Opened 2024-11-17 23:49 UTC by jsnel

Update the Dockerfiles to bundle the latest `vc_redist.x64.exe` into the images.

This is needed for certain python packages which implicitly assume these (redistributable) binaries are present on the system (see #1 for a reproducible example with `matplotlib`). 

Closes #1

2024-11-19 11:30 UTC, s-weigand requested changes
Thanks a lot for the PR, I did just build the image and didn't use it yet, so the common need for VCRedist did slip my attention.
I just have some minor improvement requests.

2024-11-19 11:30 UTC, s-weigand commented on docker/Dockerfile.server
> +LABEL org.opencontainers.image.licenses="Apache-2.0"
Not sure we can use the `licenses` label.
While the code in this repo to build the images is `Apache-2.0`, it might not be the case for the resulting image, depending on if you consider the base image as part of the image or not, as well as if the tool (`uv` and `vcredist`) licenses should also be included in the label.
I looked at the official python windows images and [they don't use any labels](https://github.com/docker-library/python/blob/2589112d847139587507c8071a80b07134a4b372/3.12/windows/windowsservercore-ltsc2022/Dockerfile).
So let's just remove it for now.

```suggestion
```

2024-11-19 11:30 UTC, s-weigand commented on docker/Dockerfile.server
> +LABEL org.opencontainers.image.version="0.0.2"
The version should be the same as the `uv` (and image tag) version
```suggestion
LABEL org.opencontainers.image.version="${UV_VERSION}"
```

2024-11-19 11:30 UTC, s-weigand commented on docker/Dockerfile.server
> +# LABEL org.opencontainers.image.authors="Sebastian Weigand <s.weigand.phy@gmail.com>"
Let's remove this, if anyone find an issue they can use the GH issue tracker (don't want mails directly and backport them to the issue tracker for transparency 😅).

2024-11-19 11:30 UTC, s-weigand commented on docker/Dockerfile.server
> +    Invoke-WebRequest -Uri $vcRedistUrl -OutFile $installerPath -UseBasicParsing; `
Let's use `WebClient.DownloadFile` since it is a lot faster for big files.
```suggestion
    (New-Object System.Net.WebClient).DownloadFile($vcRedistUrl, $installerPath); `
```

2024-11-19 11:30 UTC, s-weigand commented on docker/Dockerfile.servercore
Same as for the other `Dockerfile`.

2024-11-19 11:30 UTC, s-weigand commented on README.md
> +The repo builds 2 types of images: `server` and `servercore` with as basis respectively:
I think this makes it a bit more clear.

```suggestion
The repo builds 2 images: `server` and `servercore` with the respective base images:
```

2024-11-19 11:30 UTC, s-weigand commented on README.md
> +- mcr.microsoft.com/windows/servercore:ltsc2022
Minor readability improvement.
```suggestion
- `mcr.microsoft.com/windows/server:ltsc2022`
- `mcr.microsoft.com/windows/servercore:ltsc2022`
```

2024-11-19 11:30 UTC, s-weigand commented on docker/Dockerfile.server
> +# OCI labels for metadata
We should move all `ARG`s right below the `FROM` image so they can be used it across the image without later reordering things. And the labels below the VCRedist installation for better FS layer caching.

2024-11-19 11:30 UTC, s-weigand commented on docker/Dockerfile.server
> +RUN $vcRedistUrl='https://aka.ms/vs/17/release/vc_redist.x64.exe'; `
For layer caching this should be moved below enabling the long path support.

2024-11-19 12:04 UTC, s-weigand commented
@all-contributors please add @jsnel  for bug code doc

2024-11-20 14:31 UTC, jsnel commented on docker/Dockerfile.server
> +LABEL org.opencontainers.image.licenses="Apache-2.0"
Reviewer suggestion adopted and incorporated in commit 087e34076735b42bedc516abebf11506294b2b42.

2024-11-20 14:31 UTC, jsnel commented on docker/Dockerfile.server
> +LABEL org.opencontainers.image.version="0.0.2"
Reviewer suggestion adopted and incorporated in commit 087e34076735b42bedc516abebf11506294b2b42.

2024-11-20 14:32 UTC, jsnel commented on docker/Dockerfile.server
> +    Invoke-WebRequest -Uri $vcRedistUrl -OutFile $installerPath -UseBasicParsing; `
Reviewer suggestion adopted and incorporated in commit 087e34076735b42bedc516abebf11506294b2b42.

2024-11-20 14:32 UTC, jsnel commented on README.md
> +The repo builds 2 types of images: `server` and `servercore` with as basis respectively:
Reviewer suggestion adopted and incorporated in commit 087e34076735b42bedc516abebf11506294b2b42.

Slightly reworded again in commit b356ba0c1e1903951e6863695c4396ed28eef08a

2024-11-20 14:33 UTC, jsnel commented on docker/Dockerfile.servercore
Reviewer suggestion adopted and incorporated in commit 087e34076735b42bedc516abebf11506294b2b42.

2024-11-20 14:33 UTC, jsnel commented on docker/Dockerfile.server
> +# LABEL org.opencontainers.image.authors="Sebastian Weigand <s.weigand.phy@gmail.com>"
Reviewer suggestion adopted and incorporated in commit 087e34076735b42bedc516abebf11506294b2b42.

2024-11-20 14:33 UTC, jsnel commented on README.md
> +- mcr.microsoft.com/windows/servercore:ltsc2022
Reviewer suggestion adopted and incorporated in commit 087e34076735b42bedc516abebf11506294b2b42.

2024-11-20 14:33 UTC, jsnel commented on docker/Dockerfile.server
> +# OCI labels for metadata
Reviewer suggestion adopted and incorporated in commit 087e34076735b42bedc516abebf11506294b2b42.

2024-11-20 14:42 UTC, jsnel commented on docker/Dockerfile.server
> +RUN $vcRedistUrl='https://aka.ms/vs/17/release/vc_redist.x64.exe'; `
This was done in b22b8af0ce78533be6a3af08ea43e91eda05e9a4.

2024-11-20 15:49 UTC, s-weigand approved these changes
Thanks again for the improvement, all looks good to me now 🚀

2024-11-20 15:50 UTC, merged